name: NYT Scraper

on:
  schedule:
    - cron: "0 * * * *"  # Executa de hora em hora

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: pip install requests

      - name: Executar scraper
        run: python nytimesapi.py

      - name: Commit e push dos dados
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/St3vs/cdprojeto.git
          git add dados.json logging.log
          git commit -m "Atualização automática de artigos" || echo "Sem alterações para commit"
          git push origin main
